CUDA_VISIBLE_DEVICES=0,1 python ./source/script_training.py \
    --model 'PLAIN_CONV_RES' \
    --run_name 'loss_mse' \
    --train_data './dataset_kalan_train_patch_dior' \
    --valid_data './dataset_kalan_test' \
    --input_tonemap 'mu' \
    --label_tonemap 'mu' \
    --nChannel 3 \
    --nFeat 32 \
    --loss 'mse'\
    --loss_weights 1 \
    --epochs 40 \
    --batchsize 128
